# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
                ('run_id', models.TextField()),
                ('experiment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('run_id_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.TextField()),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('data_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.DataRun')),
            ],
        ),
        migrations.CreateModel(
            name='PlotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('data_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.DataRun')),
            ],
        ),
        migrations.AddField(
            model_name='datarun',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitting.Instrument'),
        ),
    ]
