language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "INSTALLATION_DIR = /tmp/" > neutrons/web_reflectivity/web_reflectivity/local_settings.py
#  - make install