language: python
python:
  - "2.7"
env:
  - REFL_INSTALL_DIR=/tmp

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sudo apt-get update
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda
  - conda info -a
  - conda install --yes python=$PY $NUMPYSPEC scipy cython pylint wxpython
  - pip install --upgrade codecov
install:
  - pip install django-remote-submission==1.1.7
  - pip install -r requirements.txt
script:
  - make install
  - cd /tmp/app; coverage run  manage.py test
after_success:
  - codecov
