language: python
python:
  - "2.7"
env:
  - REFL_INSTALL_DIR=/tmp
before_install:
  - pip install --upgrade codecov
install:
  - python -m pip install -U pip
  - python -m easy_install -U setuptools
  - python -m pip install wheel numpy scipy matplotlib periodictable wxPython bumps
  - pip install django-remote-submission==1.1.7
  - pip install -r requirements.txt
script:
  - make install
  - cd /tmp/app; coverage run  manage.py test
after_success:
  - codecov
